export default {
  "login": "meis",
  "id": 2230093,
  "avatar_url": "https://avatars.githubusercontent.com/u/2230093?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/meis",
  "html_url": "https://github.com/meis",
  "followers_url": "https://api.github.com/users/meis/followers",
  "following_url": "https://api.github.com/users/meis/following{/other_user}",
  "gists_url": "https://api.github.com/users/meis/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/meis/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/meis/subscriptions",
  "organizations_url": "https://api.github.com/users/meis/orgs",
  "repos_url": "https://api.github.com/users/meis/repos",
  "events_url": "https://api.github.com/users/meis/events{/privacy}",
  "received_events_url": "https://api.github.com/users/meis/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Marc Egea i Sala",
  "company": null,
  "blog": null,
  "location": null,
  "email": null,
  "hireable": true,
  "bio": null,
  "public_repos": 21,
  "public_gists": 1,
  "followers": 13,
  "following": 12,
  "created_at": "2012-08-27T21:04:02Z",
  "updated_at": "2015-06-26T14:54:09Z"
};
